name: CI – Node Demo

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Simulated Test
        run: |
          echo "Installing dependencies..."
          sleep 2
          echo "Running tests..."
          echo " All tests passed successfully!"
          echo "Building project..."
          sleep 2
          echo " Build completed successfully!"
          echo "Done."
