name: Oulu ja Ruka säätieto Teamsiin

on:
  schedule:
    - cron: "0 * * * *"   # joka tasatunti (UTC)
  workflow_dispatch:       # mahdollistaa manuaalisen ajon

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Asenna requests
        run: pip3 install --user requests

      - name: Lähetä Oulu ja Ruka -sää Teamsiin
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          python3 - << 'PY'
          import os, json, requests
          URL = "https://api.open-meteo.com/v1/forecast"
          LOCATIONS = {"Oulu": (65.0121, 25.4651), "Ruka": (66.1694, 29.1476)}
          wh = os.environ["TEAMS_WEBHOOK_URL"]
          headers = {"Content-Type":"application/json"}
          for name,(lat,lon) in LOCATIONS.items():
              r = requests.get(URL, params={
                  "latitude": lat, "longitude": lon,
                  "current_weather": True, "timezone": "Europe/Helsinki"
              }, timeout=20)
              r.raise_for_status()
              cw = r.json().get("current_weather", {})
              text = f"{name}: lämpötila {cw.get('temperature')} °C, tuuli {cw.get('windspeed')} m/s. Aikaleima {cw.get('time')}."
              resp = requests.post(wh, headers=headers, data=json.dumps({"text": text}), timeout=20)
              resp.raise_for_status()
          print("OK: viestit lähetetty Teamsiin.")
          PY

